version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-dev
    env_file:
      - wordpress.env
    networks:
      - wp_network
    volumes:
      - wordpress_data:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini           # 將 Xdebug 設定檔掛載到容器
      - ./sync-fire-wp:/var/www/html/wp-content/plugins/sync-fire   # 將 SyncFire 挂載到 WordPress
      - ./logs:/var/dev-log

networks:
  wp_network:
    external: true
    name: vscode-net
volumes:
  wordpress_data: